services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
#    environment:
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: root
#      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
