#spring:
#  application:
#    name: FreelancePlatform
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

spring:
  application:
    name: FreelancePlatform
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cpv7gctds78s73audfrg-a.frankfurt-postgres.render.com:5432/db_test_nss
    username: db_test_nss_user
    password: IkC09U7xhzVLd4RunWXrLuHoNTIKqDD9
  kafka:
    bootstrap-servers: pkc-75m1o.europe-west3.gcp.confluent.cloud:9092
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='NXXQHH3T6BDROHIX' password='sTA+qdIfwtH7jHlznzkEIoWZ4GRNduAq7KKW3AhYBzf1WS0qKCqe6o2lQwbxBph5';
      security:
        protocol: SASL_SSL
      session:
        timeout:
          ms: 45000